// Generated by npm run build:pwa. Do not edit.
const VERSION = '8faa555d8c0b07b0';
const ASSETS = [
  "LICENSE",
  "NOTICE",
  "THIRD_PARTY_NOTICES.txt",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/maskable-512.png",
  "index.html",
  "licensing.html",
  "manifest.webmanifest",
  "models.css",
  "models.html",
  "node_modules/three/LICENSE",
  "node_modules/three/build/three.core.js",
  "node_modules/three/build/three.module.js",
  "node_modules/three/examples/jsm/controls/OrbitControls.js",
  "src/app.js",
  "src/atlas.js",
  "src/chest-stone.js",
  "src/config.js",
  "src/furniture-models.js",
  "src/game.js",
  "src/guidance.js",
  "src/horizontal-shelf.js",
  "src/intro.js",
  "src/levels.js",
  "src/model-catalog.js",
  "src/model-factory.js",
  "src/model-registry.js",
  "src/model-resources.js",
  "src/models-page.js",
  "src/perimeter.js",
  "src/pushkin-portrait.js",
  "src/pwa.js",
  "src/rounded-box.js",
  "src/scene.js",
  "src/session.js",
  "styles.css"
];

// ASSETS и VERSION генерируются scripts/build-pwa.mjs по содержимому файлов.
const BASE = self.registration.scope;
const BASE_PATH = new URL(BASE).pathname;
const CACHE_PREFIX = `lost-endings:${BASE}:`;
const CACHE = `${CACHE_PREFIX}${VERSION}`;
self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await cache.addAll(ASSETS.map((asset) => new Request(new URL(asset, BASE), { cache: 'reload' })));
  })());
});
self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const name of await caches.keys()) {
      if (name.startsWith(CACHE_PREFIX) && name !== CACHE) await caches.delete(name);
    }
    await self.clients.claim();
  })());
});
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin || !url.pathname.startsWith(BASE_PATH)) return;
  let asset = url.pathname.slice(BASE_PATH.length);
  if (asset === '') asset = 'index.html';
  if (asset === 'models') asset = 'models.html';
  if (!ASSETS.includes(asset)) return;
  // HTML, модули и Three.js всегда принадлежат одной версии.
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    return (await cache.match(new URL(asset, BASE).href)) ?? fetch(event.request);
  })());
});
