import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { assets } from './site-assets.mjs';
const root = new URL('../', import.meta.url);
const worker = await readFile(new URL('scripts/service-worker.js', root), 'utf8');
const hash = createHash('sha256').update(worker);
for (const asset of assets) hash.update(asset).update(await readFile(new URL(asset, root)));
const version = hash.digest('hex').slice(0, 16);
const output = `// Generated by npm run build:pwa. Do not edit.\nconst VERSION = '${version}';\nconst ASSETS = ${JSON.stringify(assets, null, 2)};\n\n${worker}`;
if (process.argv.includes('--check')) {
  if (await readFile(new URL('sw.js', root), 'utf8') !== output) throw new Error('PWA cache is stale. Run npm run build:pwa.');
  console.log(`PWA: ${assets.length} files, cache ${version} verified`);
} else {
  await writeFile(new URL('sw.js', root), output);
  console.log(`PWA: ${assets.length} files, cache ${version}`);
}
