export const story = {
  intro: 'Письмо хранителя заканчивается странной просьбой: «Если книга обрывается, ищи то, что из неё убрали». Вы открываете детективный роман. На месте последней главы — пустые страницы.',
  ending: 'Теперь у исчезнувшего есть имя: это хранитель вашей библиотеки. На обороте восстановленной страницы проступает чужой почерк: «Не возвращай концовку. Он уже знает, что ты здесь».',
};

// # — стена, пробел — пол, @ — герой, $ — сундук, . — цель, * — сундук на цели, + — герой на цели.
// David W Skinner, Microban: первые 35 задач в исходном порядке.
// Схемы сохранены как в оригинале, включая внешние пробелы и длины строк.
export function playMap(level) {
  if (level.playRotation !== 180) return level.map;
  const width = Math.max(...level.map.map((row) => row.length));
  return level.map.map((row) => [...row.padEnd(width)].reverse().join('')).reverse();
}

export const levels = [
  {
    id: "microban-01",
    playRotation: 180,
    title: "Кабинет сыщика",
    subtitle: "Глава I",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 1, author: 'David W Skinner' },
    map: [
      "####",
      "# .#",
      "#  ###",
      "#*@  #",
      "#  $ #",
      "#  ###",
      "####",
    ],
  },
  {
    id: "microban-02",
    title: "Архив",
    subtitle: "Глава II",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 2, author: 'David W Skinner' },
    map: [
      "######",
      "#    #",
      "# #@ #",
      "# $* #",
      "# .* #",
      "#    #",
      "######",
    ],
  },
  {
    id: "microban-03",
    title: "Почтовая контора",
    subtitle: "Глава III",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 3, author: 'David W Skinner' },
    map: [
      "  ####",
      "###  ####",
      "#     $ #",
      "# #  #$ #",
      "# . .#@ #",
      "#########",
    ],
  },
  {
    id: "microban-04",
    title: "Двор под дождём",
    subtitle: "Глава IV",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 4, author: 'David W Skinner' },
    map: [
      "########",
      "#      #",
      "# .**$@#",
      "#      #",
      "#####  #",
      "    ####",
    ],
  },
  {
    id: "microban-05",
    title: "Зал допросов",
    subtitle: "Глава V",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 4. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 5, author: 'David W Skinner' },
    map: [
      " #######",
      " #     #",
      " # .$. #",
      "## $@$ #",
      "#  .$. #",
      "#      #",
      "########",
    ],
  },
  {
    id: "microban-06",
    title: "Тайник хранителя",
    subtitle: "Глава VI",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 6, author: 'David W Skinner' },
    map: [
      "###### #####",
      "#    ###   #",
      "# $$     #@#",
      "# $ #...   #",
      "#   ########",
      "#####",
    ],
  },
  {
    id: "microban-07",
    title: "Комната свидетельств",
    subtitle: "Глава VII",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 6. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 7, author: 'David W Skinner' },
    map: [
      "#######",
      "#     #",
      "# .$. #",
      "# $.$ #",
      "# .$. #",
      "# $.$ #",
      "#  @  #",
      "#######",
    ],
  },
  {
    id: "microban-08",
    title: "Старый порт",
    subtitle: "Глава I",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 8, author: 'David W Skinner' },
    map: [
      "  ######",
      "  # ..@#",
      "  # $$ #",
      "  ## ###",
      "   # #",
      "   # #",
      "#### #",
      "#    ##",
      "# #   #",
      "#   # #",
      "###   #",
      "  #####",
    ],
  },
  {
    id: "microban-09",
    title: "Островной маяк",
    subtitle: "Глава II",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 9, author: 'David W Skinner' },
    map: [
      "#####",
      "#.  ##",
      "#@$$ #",
      "##   #",
      " ##  #",
      "  ##.#",
      "   ###",
    ],
  },
  {
    id: "microban-10",
    title: "Капитанская каюта",
    subtitle: "Глава III",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 10, author: 'David W Skinner' },
    map: [
      "      #####",
      "      #.  #",
      "      #.# #",
      "#######.# #",
      "# @ $ $ $ #",
      "# # # # ###",
      "#       #",
      "#########",
    ],
  },
  {
    id: "microban-11",
    title: "Склад у причала",
    subtitle: "Глава IV",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 11, author: 'David W Skinner' },
    map: [
      "  ######",
      "  #    #",
      "  # ##@##",
      "### # $ #",
      "# ..# $ #",
      "#       #",
      "#  ######",
      "####",
    ],
  },
  {
    id: "microban-12",
    title: "Пещера приливов",
    subtitle: "Глава V",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 12, author: 'David W Skinner' },
    map: [
      "#####",
      "#   ##",
      "# $  #",
      "## $ ####",
      " ###@.  #",
      "  #  .# #",
      "  #     #",
      "  #######",
    ],
  },
  {
    id: "microban-13",
    title: "Затонувший зал",
    subtitle: "Глава VI",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 13, author: 'David W Skinner' },
    map: [
      "####",
      "#. ##",
      "#.@ #",
      "#. $#",
      "##$ ###",
      " # $  #",
      " #    #",
      " #  ###",
      " ####",
    ],
  },
  {
    id: "microban-14",
    title: "Последний остров",
    subtitle: "Глава VII",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 14, author: 'David W Skinner' },
    map: [
      "#######",
      "#     #",
      "# # # #",
      "#. $*@#",
      "#   ###",
      "#####",
    ],
  },
  {
    id: "microban-15",
    title: "Зеркальная галерея",
    subtitle: "Глава I",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 15, author: 'David W Skinner' },
    map: [
      "     ###",
      "######@##",
      "#    .* #",
      "#   #   #",
      "#####$# #",
      "    #   #",
      "    #####",
    ],
  },
  {
    id: "microban-16",
    title: "Зимний сад",
    subtitle: "Глава II",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 16, author: 'David W Skinner' },
    map: [
      " ####",
      " #  ####",
      " #     ##",
      "## ##   #",
      "#. .# @$##",
      "#   # $$ #",
      "#  .#    #",
      "##########",
    ],
  },
  {
    id: "microban-17",
    title: "Часовая башня",
    subtitle: "Глава III",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 17, author: 'David W Skinner' },
    map: [
      "#####",
      "# @ #",
      "#...#",
      "#$$$##",
      "#    #",
      "#    #",
      "######",
    ],
  },
  {
    id: "microban-18",
    title: "Парадная лестница",
    subtitle: "Глава IV",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 18, author: 'David W Skinner' },
    map: [
      "#######",
      "#     #",
      "#. .  #",
      "# ## ##",
      "#  $ #",
      "###$ #",
      "  #@ #",
      "  #  #",
      "  ####",
    ],
  },
  {
    id: "microban-19",
    title: "Зал отражений",
    subtitle: "Глава V",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 19, author: 'David W Skinner' },
    map: [
      "########",
      "#   .. #",
      "#  @$$ #",
      "##### ##",
      "   #  #",
      "   #  #",
      "   #  #",
      "   ####",
    ],
  },
  {
    id: "microban-20",
    title: "Покои хранителя",
    subtitle: "Глава VI",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 20, author: 'David W Skinner' },
    map: [
      "#######",
      "#     ###",
      "#  @$$..#",
      "#### ## #",
      "  #     #",
      "  #  ####",
      "  #  #",
      "  ####",
    ],
  },
  {
    id: "microban-21",
    title: "Башня за стеклом",
    subtitle: "Глава VII",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 21, author: 'David W Skinner' },
    map: [
      "####",
      "#  ####",
      "# . . #",
      "# $$#@#",
      "##    #",
      " ######",
    ],
  },
  {
    id: "microban-22",
    title: "Коридор черновиков",
    subtitle: "Глава I",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 22, author: 'David W Skinner' },
    map: [
      "#####",
      "#   ###",
      "#. .  #",
      "#   # #",
      "## #  #",
      " #@$$ #",
      " #    #",
      " #  ###",
      " ####",
    ],
  },
  {
    id: "microban-23",
    title: "Узкие поля",
    subtitle: "Глава II",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 23, author: 'David W Skinner' },
    map: [
      "#######",
      "#  *  #",
      "#     #",
      "## # ##",
      " #$@.#",
      " #   #",
      " #####",
    ],
  },
  {
    id: "microban-24",
    title: "Комната зачёркнутых слов",
    subtitle: "Глава III",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 24, author: 'David W Skinner' },
    map: [
      "# #####",
      "  #   #",
      "###$$@#",
      "#   ###",
      "#     #",
      "# . . #",
      "#######",
    ],
  },
  {
    id: "microban-25",
    title: "Мастерская автора",
    subtitle: "Глава IV",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 25, author: 'David W Skinner' },
    map: [
      " ####",
      " #  ###",
      " # $$ #",
      "##... #",
      "#  @$ #",
      "#   ###",
      "#####",
    ],
  },
  {
    id: "microban-26",
    title: "Переплётная",
    subtitle: "Глава V",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 26, author: 'David W Skinner' },
    map: [
      " #####",
      " # @ #",
      " #   #",
      "###$ #",
      "# ...#",
      "# $$ #",
      "###  #",
      "  ####",
    ],
  },
  {
    id: "microban-27",
    title: "Хранилище набросков",
    subtitle: "Глава VI",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 27, author: 'David W Skinner' },
    map: [
      "######",
      "#   .#",
      "# ## ##",
      "#  $$@#",
      "# #   #",
      "#.  ###",
      "#####",
    ],
  },
  {
    id: "microban-28",
    title: "Последний абзац",
    subtitle: "Глава VII",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 28, author: 'David W Skinner' },
    map: [
      "#####",
      "#   #",
      "# @ #",
      "# $$###",
      "##. . #",
      " #    #",
      " ######",
    ],
  },
  {
    id: "microban-29",
    title: "Преддверие раздела",
    subtitle: "Глава I",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 2. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 29, author: 'David W Skinner' },
    map: [
      "     #####",
      "     #   ##",
      "     #    #",
      " ######   #",
      "##     #. #",
      "# $ $ @  ##",
      "# ######.#",
      "#        #",
      "##########",
    ],
  },
  {
    id: "microban-30",
    title: "Каталог забытых книг",
    subtitle: "Глава II",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 30, author: 'David W Skinner' },
    map: [
      "####",
      "#  ###",
      "# $$ #",
      "#... #",
      "# @$ #",
      "#   ##",
      "#####",
    ],
  },
  {
    id: "microban-31",
    title: "Хранилище рукописей",
    subtitle: "Глава III",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 31, author: 'David W Skinner' },
    map: [
      "  ####",
      " ##  #",
      "##@$.##",
      "# $$  #",
      "# . . #",
      "###   #",
      "  #####",
    ],
  },
  {
    id: "microban-32",
    title: "Читальный зал",
    subtitle: "Глава IV",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 32, author: 'David W Skinner' },
    map: [
      " ####",
      "##  ###",
      "#     #",
      "#.**$@#",
      "#   ###",
      "##  #",
      " ####",
    ],
  },
  {
    id: "microban-33",
    title: "Тайная полка",
    subtitle: "Глава V",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 3. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 33, author: 'David W Skinner' },
    map: [
      "#######",
      "#. #  #",
      "#  $  #",
      "#. $#@#",
      "#  $  #",
      "#. #  #",
      "#######",
    ],
  },
  {
    id: "microban-34",
    title: "Кабинет хранителя",
    subtitle: "Глава VI",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 4. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 34, author: 'David W Skinner' },
    map: [
      "  ####",
      "###  ####",
      "#       #",
      "#@$***. #",
      "#       #",
      "#########",
    ],
  },
  {
    id: "microban-35",
    title: "Зал потерянных концовок",
    subtitle: "Глава VII",
    instruction: "Расставьте все сундуки с книгами по золотым отметкам. Сундуков: 5. Ошибочный ход можно отменить.",
    fragment: "",
    source: { collection: 'Microban', number: 35, author: 'David W Skinner' },
    map: [
      " ####",
      "##  #",
      "#. $#",
      "#.$ #",
      "#.$ #",
      "#.$ #",
      "#. $##",
      "#   @#",
      "##   #",
      " #####",
    ],
  },
];
